heligeom/views.py
import math
import pathlib
import shutil
import time
import traceback
import uuid

from flask import (
    Blueprint,
    abort,
    current_app,
    g,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from ptools.io.exceptions import InvalidPDBFormatError

from .forms import Construction, InputStructures, validate_input_structure
from .models import UserInputs, db
from .tool import (
    BeadsDifferentSizeError,
    HeligeomInterface,
    MonomersDifferentSizeError,
    MonomerSizeZeroError,
)

# Blueprint Configuration
heligeom_bp = Blueprint(
    "heligeom_bp", __name__, template_folder="templates", static_folder="static"
)

VERSION = "1.2.0"


# Functions used to time spent on each page
# TODO: Remove in production
@heligeom_bp.before_request
def log_route_start():
    g.start_time = time.time()


@heligeom_bp.after_request
def log_route_end(response):
    route = request.endpoint
    print(f"{route} ended after {time.time() - g.pop('start_time', None)}")
    return response


# Allow a global variable to passed by default to render_template()
@heligeom_bp.context_processor
def set_version():
    return dict(version=VERSION)


@heligeom_bp.route("/")
def homepage():
    return render_template("index.html")


@heligeom_bp.route("/run", methods=["GET", "POST"])
def runpage():
    # Initialize submission form
    form = InputStructures()

    print("titi")
    if request.method == "POST" and form.validate():
        print("toto")
        # Generate UUID for storing files
        uniq_id = uuid.uuid4().hex
        # Create result folder
        result_path = pathlib.Path(current_app.config["DATA_UPLOADS"], uniq_id)
        result_path.mkdir(exist_ok=True)

        pdb_filename = validate_input_structure(form.input_file, form.pdb_id, result_path)

        if pdb_filename:
            # Handle cases when monomers have different sizes or one is equal to 0
            # For that, we need to create real RigidBodys
            try:
                HeligeomInterface(
                    result_path / pathlib.Path(pdb_filename),
                    form.chain1_id.data,
                    form.chain2_id.data,
                    form.res_range1.data,
                    form.res_range2.data,
                    form.core_filter1.data,
                    form.core_region1.data,
                    form.core_region2.data,
                )
            except InvalidPDBFormatError as e:
                modalError = {
                    "title": f"File Parsing Error for {pdb_filename}",
                    "message": str(e),
                }
                shutil.rmtree(result_path)  # Removed newly created folder due to the errors
                return render_template("run.html", form=form, modalError=modalError)
            except (MonomerSizeZeroError, MonomersDifferentSizeError) as e:
                modalError = {
                    "title": "Invalid Monomer Selection for the 1st Oligomeric form",
                    "message": str(e),
                }
                shutil.rmtree(result_path)  # Removed newly created folder due to the errors
                return render_template("run.html", form=form, modalError=modalError)

            # Save to the database the form inputs
            user_inputs = UserInputs(
                request_id=uniq_id,
                pdb_filename=pdb_filename,
                chain1_id=form.chain1_id.data,
                chain2_id=form.chain2_id.data,
                res_range1=form.res_range1.data,
                res_range2=form.res_range2.data,
                core_filter1=form.core_filter1.data,
                core_region1=form.core_region1.data,
                core_filter2=form.core_filter2.data,
                core_region2=form.core_region2.data,
            )

            # Does the user input for a 2nd assembly ?
            if form.has_2nd_oligomer():
                pdb_filename_2nd = validate_input_structure(
                    form.input_file_2nd, form.pdb_id_2nd, result_path
                )
                # If no new structure is provided, use the first one
                if pdb_filename_2nd is None:
                    pdb_filename_2nd = pdb_filename

                try:
                    HeligeomInterface(
                        result_path / pathlib.Path(pdb_filename_2nd),
                        form.chain1bis_id.data,
                        form.chain2bis_id.data,
                        form.res_range1bis.data,
                        form.res_range2bis.data,
                        form.core_filter1bis.data,
                        form.core_region1bis.data,
                        form.core_region2bis.data,
                    )
                except InvalidPDBFormatError as e:
                    modalError = {
                        "title": f"File Parsing Error for {pdb_filename_2nd}",
                        "message": str(e),
                    }
                    shutil.rmtree(result_path)  # Removed newly created folder due to the errors
                    return render_template("run.html", form=form, modalError=modalError)
                except (MonomerSizeZeroError, MonomersDifferentSizeError) as e:
                    modalError = {
                        "title": "Invalid Monomer Selection for the 2nd Oligomeric form",
                        "message": str(e),
                    }
                    shutil.rmtree(result_path)  # Removed newly created folder due to the errors
                    return render_template("run.html", form=form, modalError=modalError)

                user_inputs.add_2nd_oligomer(
                    pdb_filename_2nd=pdb_filename_2nd,
                    chain1bis_id=form.chain1bis_id.data,
                    chain2bis_id=form.chain2bis_id.data,
                    res_range1bis=form.res_range1bis.data,
                    res_range2bis=form.res_range2bis.data,
                    core_filter1bis=form.core_filter1bis.data,
                    core_region1bis=form.core_region1bis.data,
                    core_filter2bis=form.core_filter2bis.data,
                    core_region2bis=form.core_region2bis.data,
                )

            # Store the input values in the database
            db.session.add(user_inputs)
            db.session.commit()

            # Redirect to the results page with correct id
            return redirect(url_for("heligeom_bp.results", results_id=uniq_id))
    return render_template("run.html", form=form)


@heligeom_bp.route("/results/<results_id>", methods=["GET", "POST"])
def results(results_id):
    # Absolute path to the result folder
    path_to_result = pathlib.Path(current_app.config["DATA_UPLOADS"], results_id)

    # Create this folder not matter what.
    # It should be done after the form submission but results are also directly accessible with the URL.
    # Useful to store the error.log file
    path_to_result.mkdir(exist_ok=True)

    # Query the database to retrieve the form inputs
    query_result = UserInputs.query.filter_by(request_id=results_id).first()

    # Redirect to 404 page when the query didn't return anything
    if not query_result:
        abort(404)

    # Path for all output files accessible to the user
    pdb_monomers = "mono1-2.pdb"
    contacts_csv = "contacts_interface1.csv"

    try:
        # Extract data from the database
        pdb_filename = query_result.pdb_filename
        chain1_id = query_result.chain1_id
        chain2_id = query_result.chain2_id
        res_range1 = query_result.res_range1
        res_range2 = query_result.res_range2
        core_filter1 = query_result.core_filter1
        core_region1 = query_result.core_region1
        core_filter2 = query_result.core_filter2
        core_region2 = query_result.core_region2

        pdb_abs_path = path_to_result / pdb_filename

        # Object to handle all the computation
        heli_interface1 = HeligeomInterface(
            pdb_abs_path,
            chain1_id,
            chain2_id,
            res_range1,
            res_range2,
            core_filter1,
            core_region1,
            core_region2,
        )

        # Save monomers only for the 1st molstar visualisation, depicting the interface
        heli_interface1.save_monomers(path_to_result / pdb_monomers)

        # Compute Helicoidal parameters
        pitch, monomers_per_turn, direction, dmin, dmax, rmsd = heli_interface1.compute_screw()

        # Information passed to the jinja2 template
        screw_data = {
            "results_id": results_id,
            "pdb_input": pdb_filename,
            "monos_file": pdb_monomers,
            "chain1_id": chain1_id,
            "chain2_id": chain2_id,
            "res_range1": res_range1,
            "res_range2": res_range2,
            "core_filter1": core_filter1,
            "core_region1": core_region1,
            "core_filter2": core_filter2,
            "core_region2": core_region2,
            "pitch": f"{pitch:3.2f}",
            "nb_monomers": f"{monomers_per_turn:3.2f}",
            "direction": direction,
            "rotation_angle": f"{heli_interface1.hp.angle:3.2f}",
            "rotation_angle_deg": f"{math.degrees(heli_interface1.hp.angle):3.2f}",
            "axis_point": [f"{coord:3.2f}" for coord in heli_interface1.hp.point],
            "translation": f"{heli_interface1.hp.normtranslation:3.2f}",
            "dmin": f"{dmin:3.2f}",
            "dmax": f"{dmax:3.2f}",
            "rmsd": f"{rmsd:3.2f}",
            "select_interface_mono": heli_interface1.molstar_selection_monomers(
                path_to_result / contacts_csv
            ),
            "select_core1": heli_interface1.molstar_select_core_monomer1,
            "select_core2": heli_interface1.molstar_select_core_monomer2,
            "contacts_csv": contacts_csv,
        }

        # 2nd Oligomer
        has_2nd_oligo = False
        screw_data_bis = dict()
        heli_interface2 = None

heligeom/templates/about.html
{% extends 'base.html' %}

{% block title %}Heligeom - Help{% endblock %}

{% block content %}


<div class="container">
  <div class="section">
    <div class="row">
      <div class="col s12 m9 l10">

        <div  class="section scrollspy" id="about" style="padding-top: 0px; padding-bottom: 0px;">
          <h3 class="header light blue-grey-text text-darken-3">About Heligeom</h3>
          <p>
          <b>Heligeom aims at characterizing, manipulating and assembling structural units with a screw organization,
            in which the structural units may be individual proteins or protein hetero-multimers.<br/>
          </b>
          Heligeom relies on structures of monomer-monomer interfaces both for defining the transformation and for constructing representative filaments. <br />
          </p>

        </div> <!-- end div scrollspy -->

        <div  class="section scrollspy" id="screw" style="padding-top: 0px;padding-bottom: 0px;">
          <h5 class="title_card_results">Screw & Helical Parameters</h5>

          <p>
            Heligeom is based on a representation of an arbitrary spatial displacement of a rigid body in terms of a screw transformation.<br />
          </p>
          <p>
            A screw motion is defined by the six degrees of freedom associated with a rotation in 3D around a specified axis and a translation along this axis.
            <br>
            <img class="center" src="{{ url_for('static', filename='img/Fig1.png')}}" style="width: 600px;">
            <figcaption class="center"><i><font size="">Transformation from rigid body A to rigid body B is obtained
              via a Screw transformation of angle θ and translation 'trans' with respect to the (P, Ω) axis.</font></i></figcaption>

            <br>
            <br>
            The Heligeom webserver is based on the <a href="https://github.com/ptools/ptools">PTools library</a>,
            in which screw motions are calculated and stored in a compact implementation from the 4x4 rotation-translation matrix provided by superposition of the input protein monomers. The user may also specify a quasi-rigid  <b>core</b> region of the input proteins for defining the screw transformation.
          </p>
          <p>
            The screw transformation is defined by:
            <ul class="browser-default">
              <li>the position <b>P</b> and direction <b>Ω</b> of a screw axis</li>
              <li>a rotation <b>θ</b> around this axis</li>
              <li>a translation <b>trans</b> parallel to the axis</li>
            </ul>
          </p>
          <p>
            Parameters describing the helix or ring shape, i.e. the <b>pitch</b>, the number of monomers per turn <b>nb</b> and the direction of rotation <b>dir</b>,
            are derived from the screw parameters as follows:
          </p>
          <math display="block">
            <mtable>
            <mtr>
              <mtd>
              <mi>nb</mi>
            </mtd>
          <mtd>
              <mo>=</mo>
            </mtd>
          <mtd>
              <mfrac>
                <mn>360</mn>
                <mn>θ</mn>
              </mfrac>
            </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>pitch</mi>
              </mtd>
              <mtd>
                <mo>=</mo>
              </mtd>
              <mtd>
                <mi>nb</mi>
                <mo>x</mo>
                <mi>trans</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>dir</mi>
              </mtd>
              <mtd>
                <mo>=</mo>
              </mtd>
              <mtd>
                <mrow>
                  <mo>{</mo>
                    <mtable>
                      <mtr><mtd>
                        <mn>Right</mn> if <mo>(</mo> <mn>θ</mn> <mo>x</mo> <mi>trans</mi> <mo>)</mo>  <mo>></mo> <mn>0</mn>
                      </mtd></mtr>
                      <mtr><mtd>
                        <mn>Left</mn> if <mo>(</mo><mn>θ</mn> <mo>x</mo> <mi>trans</mi> <mo>)</mo> <mo><</mo> <mn>0</mn>
                      </mtd></mtr>
                    </mtable>
                  </mrow>
              </mtd>
            </mtr>
          </mtable>
          </math>
          <br>
          <br>
          <div class="row">
            <div class="col s12 m6 l6">
              <ul class="browser-default">
                <li>The <b>pitch</b> is the distance of one helical turn measured along the helix axis.</li>
                <li>The <b>monomer per turn</b> is the number of monomers needed for exactly one turn of the helix.</li>
                <li>The <b>Handedness</b> is the direction of rotation around the axis.</li>
                <li>The 2 distances (<b>IntR</b> and <b>ExtR</b>) are the minimal and maximal distances between the screw axis and the atoms of the oligomeric filament.</li>
              </ul>
            </div>
            <div class="col s12 m4 l4">
              <img class="responsive-img" src="{{ url_for('static', filename='img/helical_parameters_sketch.png')}}"style="max-width:75%;">
            </div>
          </div>
        </div> <!-- end div scrollspy -->

        <div  class="section scrollspy" id="about" style="padding-top: 0px; padding-bottom: 0px;">
          <h5 class="title_card_results">Comparison of interfaces</h5>
          <p>
            If two interfaces are provided, the server provides both sets of helical parameters
            and additionally computes the <b>fNAT</b> : the fraction of residue-residue contacts shared in the two interfaces,
             which is a measure of interface similarity commonly used to evaluate protein-protein docking predictions
             (see <a href="{{ url_for('heligeom_bp.homepage', _anchor='interfaces') }}">the home page</a> for an example.)
          </p>

        </div> <!-- end div scrollspy -->

        <div  class="section scrollspy" id="construction" style="padding-top: 0px; padding-bottom: 0px;">
          <h5 class="title_card_results">Construction of one oligomer</h5>
          <p>
            Based on the Screw geometry, the Heligeom web server can construct structures of desired length (the number of assembled monomers is limited to 100), which can be downloaded as .pdb or .mmcif files.
            For convenience, the server can be requested to align the helix axis of the generated complex with the Z-axis.<br>
            In case the helical analysis has been restricted to a core protein region (see above), the whole protein may nevertheless be used for construction, in which case
            all regions will undergo the screw transformation defined by the core region.
          </p>
        </div> <!-- end div scrollspy -->

        <div  class="section scrollspy" id="flatten" style="padding-top: 0px; padding-bottom: 0px;">
          <h5 class="title_card_results">Targeted adjustment (i.e Flattening)</h5>
          <p>
            Heligeom can be used to adjust an experimental or a predicted helical assembly having a small pitch and a number of monomers per turn close to an integer value <i>N</i>
            to attain a ring structure, with zero pitch and precisely <i>N</i> monomers per turn, using a method described in [1].<br>
            <br>
            In short, after calculating the screw parameters for two interacting subunits, the adjustment process consists
            in slightly re-positioning and re-orienting the first subunit with respect to the screw axis, which is kept fixed, in such a way that
            an acceptable interaction energy is obtained between subunit 1 and its image
            obtained via rotation by 2π/N in the plane perpendicular to the axis.<br><br>
            Initial radial positioning of the first subunit center of mass with respect to the axis is evaluated using simple geometrical considerations.<br><br>
            Subsequently, an exploration is carried out using concerted rigid-body moves consisting of radial translations of the interacting subunits and rotations around their centers of mass,
			which are accepted or rejected based on a Metropolis Monte Carlo criterion.<br><br>
            The process employs a reduced representation of the proteins [2] in order to decrease the sensitivity to side chain conformational variability at the interface.
          </p>
        </div> <!-- end div scrollspy -->

        <div  class="section scrollspy" id="references" style="padding-top: 0px;">
          <h5 class="title_card_results">References</h5>
          <p>
            <ol>
                <li>Boyer B, Ezelin J, Poulain P, Saladin A, Zacharias M, Robert C H, and Prévost C (2015)
                    <b>An Integrative Approach to the Study of Filamentous Oligomeric Assemblies, with Application to RecA.</b> PLOS ONE 10(3): e0116414.
                    <a href=https://doi.org/10.1371/journal.pone.0116414>https://doi.org/10.1371/journal.pone.0116414</a><br /></li>
                <li>
                  M. Zacharias (2003)
                  <b>Protein-protein docking with a reduced protein modelaccounting for side-chain flexibility</b>, Protein Sci 12 (6)  1271–1282
                  <A href="https://doi.org/10.1110/ps.0239303">https://doi.org/10.1110/ps.0239303</A>
                </li>
            </ol>
        </p>

        </div> <!-- end div scrollspy -->


      </div> <!-- end div col s12 m9 l10-->

    <div class="col hide-on-small-only m3 l2">
      <div class="pinned" style="top: 70px;">
        <ul class="section table-of-contents">
          <li><a href="#about">About</a></li>
          <li><a href="#screw">Screw transformation</a></li>
          <li><a href="#construction">Construction</a></li>
          <li><a href="#flatten">Flattening</a></li>
          <li><a href="#references">References</a></li>
        </ul>
      </div>
    </div> <!-- end div col hide-on-small-only m3 l2-->


    </div> <!-- end div row-->
  </div> <!-- end div section-->
</div> <!-- end div container-->
{% endblock %}

heligeom/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block title %}Home{% endblock %}</title>

  <!-- Illustration from NIAID Visual & Medical Arts. 08/28/2024. Filovirus. NIAID BIOART Source. bioart.niaid.nih.gov/bioart/2182 -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='img/favico/apple-touch-icon.png')}}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='img/favico/favicon-32x32.png')}}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='img/favico/favicon-16x16.png')}}">
  <link rel="manifest" href="{{url_for('static', filename='img/favico/site.webmanifest')}}">

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/materialize.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{{ url_for('static', filename='css/style.css') }}" type="text/css" rel="stylesheet" media="screen,projection"/>

  <!-- MOLSTAR Web Component -->
  <!-- Required for IE11 -->
  <script src="https://cdn.jsdelivr.net/npm/babel-polyfill/dist/polyfill.min.js"></script>
  <!-- Web component polyfill (only loads what it needs) -->
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs/webcomponents-lite.js" charset="utf-8"></script>
  <!-- Required to polyfill modern browsers as code is ES5 for IE... -->
  <script src="https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js" charset="utf-8"></script>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.3.0/build/pdbe-molstar-light.css" />
  <!-- JS -->
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pdbe-molstar@3.3.0/build/pdbe-molstar-component.js"></script>
<!-- END MOLSTAR Web Component -->


</head>
<body>
    <div class="content">
    {% include "navbar.html" %}

    {% block content %}{% endblock %}

    </div>
    {% include "footer.html" %}
</body>
</html>

heligeom/templates/contact.html
{% extends 'base.html' %}

{% block title %}Heligeom - Run{% endblock %}

{% block content %}


  <div class="container">
    <div class="section contacts">

        <h2 class="header light blue-grey-text text-darken-3"">Contact</h2>
        <div class="row">
            <div class="col l5 s12">
                <h5 class="blue-grey-text text-darken-3 center">Created by</h5>
                <p class="center">
                    <b>Hubert Santuz </b><br />
                    <b>Benoist Laurent</b><br />
                    <b>Chantal Prévost</b><br />
                    <b>Charles Robert</b><br />
                </p>
            </div>
            <div class="col l2 s12">
                <img class="circle responsive-img" src="{{ url_for('static', filename='img/ibpc-batiment.jpg') }}">
            </div>
            <div class="col l5 s12">
                <h5 class="blue-grey-text text-darken-3" style="margin-top: 0;">Address</h5>
                <p class="light">
                <b>Laboratoire de Biochimie Théorique</b><br />
                UPR 9080 CNRS<br/>
                Institut de Biologie Physico-Chimique<br/>
                13 rue Pierre et Marie Curie<br/>
                75005 Paris, France<br/>
                <i class="tiny material-icons contact-icons">computer</i> <a href="http://www-lbt.ibpc.fr/">www-lbt.ibpc.fr/</a><br />
                </p>
            </div>
        </div>


        <h2 class="header light blue-grey-text text-darken-3">Support & Troubleshooting</h2>

        <p>
            If you have found issues or bugs, have questions, or would like to suggest improvements, you can:
            <ul class="browser-default">
                <li>Use the <a href="https://github.com/ptools/heligeom_webserver/issues">Issue Tracker</a> of the repository.</li>
                <li>Send us an email to this address: <b>hubert.santuz[at]ibpc.fr</b></li>
            </ul>
        </p>


        <h2 class="header light blue-grey-text text-darken-3">Sources</h2>

        <p>
            The source code of the webserver is available on Github: <a href="https://github.com/ptools/heligeom_webserver">https://github.com/ptools/heligeom_webserver</a>
             and archived in Software Heritage (<a href="https://archive.softwareheritage.org/swh:1:dir:af308bc8009c2d889d6cd42c29198ecb50e7fd25;origin=https://github.com/ptools/heligeom_webserver;visit=swh:1:snp:17e03b8881aa89e8fdda8727b572f3897a9eac9c;anchor=swh:1:rev:e07989aa780a79ae6a602d7d30e1081b3d6b2fc7">swh:1:dir:af308bc8009c2d889d6cd42c29198ecb50e7fd25</a>).
        </p>
        <p>
            This webserver relies on a library called <b>Ptools</b> (1-2) whose source code is available here: <a href="https://github.com/ptools/ptools">https://github.com/ptools/ptools</a>.
        </p>
		<p>
		The molecule viewer plugin used on this website is based on <a href="https://molstar.org">Mol* Viewer</a> (3).
		</p>


        <h2 class="header light blue-grey-text text-darken-3">Citation</h2>

        <p>
		<b>If you use the Heligeom webserver, please cite:</b>
        </p>

		<p>
		Santuz H, Laurent B, Robert CH, and Prévost C (2025) <b>Heligeom: A web resource to generate, analyze, and visualize filament architectures based on pairwise association geometries of biological macromolecules.</b> Journal of Molecular Biology.
        <a href="https://doi.org/10.1016/j.jmb.2025.169019">https://doi.org/10.1016/j.jmb.2025.169019</a>
		</p>

        <h2 class="header light blue-grey-text text-darken-3">References</h2>

        <p>
            <ol>
                <li>Boyer B, Ezelin J, Poulain P, Saladin A, Zacharias M, Robert C H, and Prévost C (2015)
                    <b>An Integrative Approach to the Study of Filamentous Oligomeric Assemblies, with Application to RecA.</b> PLOS ONE 10(3): e0116414.
                    <a href=https://doi.org/10.1371/journal.pone.0116414>https://doi.org/10.1371/journal.pone.0116414</a><br /></li>
                <li>
                    A. Saladin, S. Fiorucci, P. Poulain, C. Prévost and M. Zacharias (2009).
                    <b>PTools: an opensource molecular docking library.</b> BMC Structural Biology 9, 27-37
                    <a href=https://doi.org/10.1186/1472-6807-9-27>https://doi.org/10.1186/1472-6807-9-27</a>
                </li>
                <li>David Sehnal, Sebastian Bittrich, Mandar Deshpande, Radka Svobodová, Karel Berka, Václav Bazgier, Sameer Velankar, Stephen K Burley, Jaroslav Koča, Alexander S Rose. (2021)
                    <b>Mol* Viewer: modern web app for 3D visualization and analysis of large biomolecular structures.</b>
                    Nucleic Acids Research, Volume 49, Issue W1, 2 July 2021, Pages W431–W437
                    <a href="https://doi.org/10.1093/nar/gkab314">https://doi.org/10.1093/nar/gkab314</a></li>
            </ol>
        </p>

    </div>
  </div>



  {% endblock %}

heligeom/templates/error.html
{% extends 'base.html' %}

{% block title %}Heligeom - Run{% endblock %}

{% block content %}


  <div class="container">
    <div class="section">

        <br>
        <br>

        <h5 class="header center red-text">Something went wrong while processing data</h5>

        {% if summary %}
          <h6 class="header center red-text">{{ summary }} </h6>
        {%endif %}

    <div>
      <button class="btn waves-effect waves-light" onclick="showErrorLogs()">Show Error</button>
      <pre id="logs" style="display: none;">
        <code>
          {{ error_log}}
        </code>
    </pre>
    </div>
    </div>
  </div>



  {% endblock %}

heligeom/templates/navbar.html
<nav class="lbt-bleu" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{{ url_for('heligeom_bp.homepage')}}" class="brand-logo">Heligeom</a>
    <ul class="nav-left hide-on-med-and-down">
        <li><a href="{{ url_for('heligeom_bp.homepage')}}">Home</a></li>
        <li><a href="{{ url_for('heligeom_bp.runpage')}}">Run</a></li>
        <li><a href="{{ url_for('heligeom_bp.help')}}">Help</a></li>
        <li><a href="{{ url_for('heligeom_bp.examples')}}">Examples</a></li>
        <li><a href="{{ url_for('heligeom_bp.about')}}">About</a></li>
        <li><a href="{{ url_for('heligeom_bp.contact')}}">Contact</a></li>
    </ul>

    <ul id="nav-mobile" class="sidenav">
        <li><a href="{{ url_for('heligeom_bp.homepage')}}">Home</a></li>
        <li><a href="{{ url_for('heligeom_bp.runpage')}}">Run</a></li>
        <li><a href="{{ url_for('heligeom_bp.help')}}">Help</a></li>
        <li><a href="{{ url_for('heligeom_bp.examples')}}">Examples</a></li>
        <li><a href="{{ url_for('heligeom_bp.about')}}">About</a></li>
        <li><a href="{{ url_for('heligeom_bp.contact')}}">Contact</a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>